In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import KFold
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix

In [2]:
df=pd.read_csv('./train4.csv')
pd.set_option('display.max_row', None)
display(df)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     37    1   2       130   250    0        1      187      0      3.5   
1     41    0   1       130   204    0        0      172      0      1.4   
2     57    0   0       120   354    0        1      163      1      0.6   
3     57    1   0       140   192    0        1      148      0      0.4   
4     44    1   1       120   263    0        1      173      0      0.0   
5     52    1   2       172   199    1        1      162      0      0.5   
6     54    1   0       140   239    0        1      160      0      1.2   
7     48    0   2       130   275    0        1      139      0      0.2   
8     49    1   1       130   266    0        1      171      0      0.6   
9     64    1   3       110   211    0        0      144      1      1.8   
10    66    0   3       150   226    0        1      114      0      2.6   
11    43    1   0       150   247    0        1      171      0      1.5   
12    69    0   3       140   239    0        1      151      0      1.8   
13    59    1   0       135   234    0        1      161      0      0.5   
14    44    1   2       130   233    0        1      179      1      0.4   
15    42    1   0       140   226    0        1      178      0      0.0   
16    61    1   2       150   243    1        1      137      1      1.0   
17    40    1   3       140   199    0        1      178      1      1.4   
18    71    0   1       160   302    0        1      162      0      0.4   
19    59    1   2       150   212    1        1      157      0      1.6   
20    65    0   2       140   417    1        0      157      0      0.8   
21    53    1   2       130   197    1        0      152      0      1.2   
22    41    0   1       105   198    0        1      168      0      0.0   
23    65    1   0       120   177    0        1      140      0      0.4   
24    44    1   1       130   219    0        0      188      0      0.0   
25    54    1   2       125   273    0        0      152      0      0.5   
26    51    1   3       125   213    0        0      125      1      1.4   
27    46    0   2       142   177    0        0      160      1      1.4   
28    54    0   2       135   304    1        1      170      0      0.0   
29    54    1   2       150   232    0        0      165      0      1.6   
30    65    0   2       160   360    0        0      151      0      0.8   
31    48    1   1       130   245    0        0      180      0      0.2   
32    45    1   0       104   208    0        0      148      1      3.0   
33    53    0   0       130   264    0        0      143      0      0.4   
34    39    1   2       140   321    0        0      182      0      0.0   
35    47    1   2       138   257    0        0      156      0      0.0   
36    53    0   0       138   234    0        0      160      0      0.0   
37    51    0   2       130   256    0        0      149      0      0.5   
38    66    1   0       120   302    0        0      151      0      0.4   
39    62    1   2       130   231    0        1      146      0      1.8   
40    44    0   2       108   141    0        1      175      0      0.6   
41    63    0   2       135   252    0        0      172      0      0.0   
42    52    1   1       134   201    0        1      158      0      0.8   
43    48    1   0       122   222    0        0      186      0      0.0   
44    45    1   0       115   260    0        0      185      0      0.0   
45    34    1   3       118   182    0        0      174      0      0.0   
46    54    1   1       108   309    0        1      156      0      0.0   
47    52    1   3       118   186    0        0      190      0      0.0   
48    41    1   1       135   203    0        1      132      0      0.0   
49    58    1   2       140   211    1        0      165      0      0.0   
50    35    0   0       138   183    0        1      182      0      1.4   
51    51    1   2       100   222    0        1      

In [3]:
df.nunique()

age          41
sex           2
cp            4
trestbps     43
chol        136
fbs           2
restecg       3
thalach      88
exang         2
oldpeak      37
slope         3
ca            4
thal          3
target        2
dtype: int64

In [4]:
df.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object

In [5]:
df['ca'].unique()

array([0, 2, 1, 3], dtype=int64)

In [6]:
df.ca.value_counts()

0    144
1     50
2     32
3     16
Name: ca, dtype: int64

In [7]:
df[df['ca']==4]

Empty DataFrame
Columns: [age, sex, cp, trestbps, chol, fbs, restecg, thalach, exang, oldpeak, slope, ca, thal, target]
Index: []

In [8]:
df.loc[df['ca']==4, 'ca']=np.NaN

In [9]:
df['ca'].unique()

array([0., 2., 1., 3.])

In [10]:
df.thal.value_counts()

2    133
3     94
1     15
Name: thal, dtype: int64

In [11]:
df[df['thal']==0]

Empty DataFrame
Columns: [age, sex, cp, trestbps, chol, fbs, restecg, thalach, exang, oldpeak, slope, ca, thal, target]
Index: []

In [12]:
df.loc[df['thal']==0,'thal']=np.NaN

In [13]:
df['thal'].unique()

array([2., 1., 3.])

In [14]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [15]:
df = df.fillna(df.median())

In [16]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [17]:
duplicated = df[df.duplicated(keep=False)]
duplicated.head()

Empty DataFrame
Columns: [age, sex, cp, trestbps, chol, fbs, restecg, thalach, exang, oldpeak, slope, ca, thal, target]
Index: []

In [18]:
duplicated = df.duplicated().sum()
if duplicated:
    print('Duplicates Row in Dataset are : {}'.format(duplicated))
else:
        print('Dataset contains no Duplicate values')

Dataset contains no Duplicate values


In [19]:
df.drop_duplicates(keep='first', inplace=True)

In [20]:
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     37    1   2       130   250    0        1      187      0      3.5   
1     41    0   1       130   204    0        0      172      0      1.4   
2     57    0   0       120   354    0        1      163      1      0.6   
3     57    1   0       140   192    0        1      148      0      0.4   
4     44    1   1       120   263    0        1      173      0      0.0   
5     52    1   2       172   199    1        1      162      0      0.5   
6     54    1   0       140   239    0        1      160      0      1.2   
7     48    0   2       130   275    0        1      139      0      0.2   
8     49    1   1       130   266    0        1      171      0      0.6   
9     64    1   3       110   211    0        0      144      1      1.8   
10    66    0   3       150   226    0        1      114      0      2.6   
11    43    1   0       150   247    0        1      171      0      1.5   
12    69    0   3       140   239    0        1      151      0      1.8   
13    59    1   0       135   234    0        1      161      0      0.5   
14    44    1   2       130   233    0        1      179      1      0.4   
15    42    1   0       140   226    0        1      178      0      0.0   
16    61    1   2       150   243    1        1      137      1      1.0   
17    40    1   3       140   199    0        1      178      1      1.4   
18    71    0   1       160   302    0        1      162      0      0.4   
19    59    1   2       150   212    1        1      157      0      1.6   
20    65    0   2       140   417    1        0      157      0      0.8   
21    53    1   2       130   197    1        0      152      0      1.2   
22    41    0   1       105   198    0        1      168      0      0.0   
23    65    1   0       120   177    0        1      140      0      0.4   
24    44    1   1       130   219    0        0      188      0      0.0   
25    54    1   2       125   273    0        0      152      0      0.5   
26    51    1   3       125   213    0        0      125      1      1.4   
27    46    0   2       142   177    0        0      160      1      1.4   
28    54    0   2       135   304    1        1      170      0      0.0   
29    54    1   2       150   232    0        0      165      0      1.6   
30    65    0   2       160   360    0        0      151      0      0.8   
31    48    1   1       130   245    0        0      180      0      0.2   
32    45    1   0       104   208    0        0      148      1      3.0   
33    53    0   0       130   264    0        0      143      0      0.4   
34    39    1   2       140   321    0        0      182      0      0.0   
35    47    1   2       138   257    0        0      156      0      0.0   
36    53    0   0       138   234    0        0      160      0      0.0   
37    51    0   2       130   256    0        0      149      0      0.5   
38    66    1   0       120   302    0        0      151      0      0.4   
39    62    1   2       130   231    0        1      146      0      1.8   
40    44    0   2       108   141    0        1      175      0      0.6   
41    63    0   2       135   252    0        0      172      0      0.0   
42    52    1   1       134   201    0        1      158      0      0.8   
43    48    1   0       122   222    0        0      186      0      0.0   
44    45    1   0       115   260    0        0      185      0      0.0   
45    34    1   3       118   182    0        0      174      0      0.0   
46    54    1   1       108   309    0        1      156      0      0.0   
47    52    1   3       118   186    0        0      190      0      0.0   
48    41    1   1       135   203    0        1      132      0      0.0   
49    58    1   2       140   211    1        0      165      0      0.0   
50    35    0   0       138   183    0        1      182      0      1.4   
51    51    1   2       100   222    0        1      

In [21]:
x_train=df.values
x_train=np.delete(x_train,13,axis=1)
y_train=df['target'].values

In [22]:
from sklearn.naive_bayes import GaussianNB
modelnb = GaussianNB()

In [23]:
x_train

array([[37.,  1.,  2., ...,  0.,  0.,  2.],
       [41.,  0.,  1., ...,  2.,  0.,  2.],
       [57.,  0.,  0., ...,  2.,  0.,  2.],
       ...,
       [45.,  1.,  3., ...,  1.,  0.,  3.],
       [68.,  1.,  0., ...,  1.,  2.,  3.],
       [57.,  1.,  0., ...,  1.,  1.,  3.]])

In [24]:
modelnb.fit(x_train,y_train)

GaussianNB()

In [26]:
dt=pd.read_csv('./testk4.csv')
display(dt)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0    63    1   3       145   233    1        0      150      0      2.3   
1    56    1   1       120   236    0        1      178      0      0.8   
2    56    0   1       140   294    0        0      153      0      1.3   
3    57    1   2       150   168    0        1      174      0      1.6   
4    58    0   3       150   283    1        0      162      0      1.0   
5    50    0   2       120   219    0        1      158      0      1.6   
6    58    0   2       120   340    0        1      172      0      0.0   
7    51    1   2       110   175    0        1      123      0      0.6   
8    65    0   2       155   269    0        1      148      0      0.8   
9    51    0   2       140   308    0        0      142      0      1.5   
10   52    1   1       120   325    0        1      172      0      0.2   
11   44    1   2       140   235    0        0      180      0      0.0   
12   53    0   2       128   216    0        0      115      0      0.0   
13   57    0   0       128   303    0        0      159      0      0.0   
14   71    0   2       110   265    1        0      130      0      0.0   
15   45    0   1       130   234    0        0      175      0      0.6   
16   43    0   2       122   213    0        1      165      0      0.2   
17   68    1   2       118   277    0        1      151      0      1.0   
18   46    1   1       101   197    1        1      156      0      0.0   
19   54    0   1       132   288    1        0      159      1      0.0   
20   42    1   2       120   240    1        1      194      0      0.8   
21   50    1   2       129   196    0        1      163      0      0.0   
22   50    0   0       110   254    0        0      159      0      0.0   
23   64    0   0       180   325    0        1      154      1      0.0   
24   41    1   2       130   214    0        0      168      0      2.0   
25   56    1   3       120   193    0        0      162      0      1.9   
26   59    1   0       138   271    0        0      182      0      0.0   
27   41    1   1       110   235    0        1      153      0      0.0   
28   64    1   0       128   263    0        1      105      1      0.2   
29   51    0   2       120   295    0        0      157      0      0.6   
30   70    1   1       156   245    0        0      143      0      0.0   
31   42    1   2       130   180    0        1      150      0      0.0   
32   66    0   2       146   278    0        0      152      0      0.0   
33   35    1   1       122   192    0        1      174      0      0.0   
34   38    1   2       138   175    0        1      173      0      0.0   
35   58    1   2       132   224    0        0      173      0      3.2   
36   43    1   0       120   177    0        0      120      1      2.5   
37   58    1   2       112   230    0        0      165      0      2.5   
38   51    0   0       130   305    0        1      142      1      1.2   
39   60    1   2       140   185    0        0      155      0      3.0   
40   65    1   0       110   248    0        0      158      0      0.6   
41   49    1   2       120   188    0        1      139      0      2.0   
42   39    1   0       118   219    0        1      140      0      1.2   
43   65    1   0       135   254    0        0      127      0      2.8   
44   63    0   0       150   407    0        0      154      0      4.0   
45   56    0   0       200   288    1        0      133      1      4.0   
46   35    1   0       120   198    0        1      130      1      1.6   
47   55    1   0       160   289    0        0      145      1      0.8   
48   70    1   0       130   322    0        0      109      0      2.4   
49   51    1   0       140   299    0        1      173      1      1.6   
50   58    1   0       125   300    0        0      171      0      0.0   
51   70    1   2       160   269    0        1      112      1      2.9   
52   69    1   2       140   

In [27]:
x_test=dt.values
x_test=np.delete(x_test,13,axis=1)
y_test=dt['target'].values

In [28]:
y_pred_prob=modelnb.predict_proba(x_test)
y_pred_prob

array([[7.08469534e-01, 2.91530466e-01],
       [6.30082914e-03, 9.93699171e-01],
       [2.70208753e-02, 9.72979125e-01],
       [6.52238353e-03, 9.93477616e-01],
       [1.25553906e-03, 9.98744461e-01],
       [2.51184041e-03, 9.97488160e-01],
       [2.36278906e-04, 9.99763721e-01],
       [9.56318431e-03, 9.90436816e-01],
       [2.38576723e-03, 9.97614233e-01],
       [1.16508142e-02, 9.88349186e-01],
       [4.54190874e-03, 9.95458091e-01],
       [1.28851098e-03, 9.98711489e-01],
       [5.60310953e-03, 9.94396890e-01],
       [1.71499840e-02, 9.82850016e-01],
       [2.12059277e-02, 9.78794072e-01],
       [1.98919479e-03, 9.98010805e-01],
       [2.80966148e-04, 9.99719034e-01],
       [1.46716199e-01, 8.53283801e-01],
       [5.32938526e-02, 9.46706147e-01],
       [2.30437637e-01, 7.69562363e-01],
       [6.34719489e-02, 9.36528051e-01],
       [1.39719596e-03, 9.98602804e-01],
       [3.27447375e-03, 9.96725526e-01],
       [4.21969002e-01, 5.78030998e-01],
       [1.969307

In [29]:
y_test

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [30]:
prediksi = modelnb.predict(x_test)
prediksi

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1], dtype=int64)

In [32]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, prediksi)

array([[22,  3],
       [ 2, 33]], dtype=int64)

In [34]:
from sklearn.metrics import classification_report
print(classification_report(y_test, prediksi))

              precision    recall  f1-score   support

           0       0.92      0.88      0.90        25
           1       0.92      0.94      0.93        35

    accuracy                           0.92        60
   macro avg       0.92      0.91      0.91        60
weighted avg       0.92      0.92      0.92        60



In [35]:
test = [[63,1,3,145,233,1,0,150,0,2.3,0,0,1]]
predicted2= modelnb.predict(test)
print("hasil prediksi :"),predicted2

hasil prediksi :


(None, array([0], dtype=int64))

In [36]:
predicted2_proba=modelnb.predict_proba(test)
print("hasil probabilitas:"),predicted2_proba

hasil probabilitas:


(None, array([[0.70846953, 0.29153047]]))