In [1]:
import pandas as pd
from IPython.display import display
import numpy as np

from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix

In [2]:
df=pd.read_csv('./heart.csv')
pd.set_option('display.max_row', None)
display(df)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
5     57    1   0       140   192    0        1      148      0      0.4   
6     56    0   1       140   294    0        0      153      0      1.3   
7     44    1   1       120   263    0        1      173      0      0.0   
8     52    1   2       172   199    1        1      162      0      0.5   
9     57    1   2       150   168    0        1      174      0      1.6   
10    54    1   0       140   239    0        1      160      0      1.2   
11    48    0   2       130   275    0        1      139      0      0.2   
12    49    1   1       130   266    0        1      171      0      0.6   
13    64    1   3       110   211    0        0      144      1      1.8   
14    58    0   3       150   283    1        0      162      0      1.0   
15    50    0   2       120   219    0        1      158      0      1.6   
16    58    0   2       120   340    0        1      172      0      0.0   
17    66    0   3       150   226    0        1      114      0      2.6   
18    43    1   0       150   247    0        1      171      0      1.5   
19    69    0   3       140   239    0        1      151      0      1.8   
20    59    1   0       135   234    0        1      161      0      0.5   
21    44    1   2       130   233    0        1      179      1      0.4   
22    42    1   0       140   226    0        1      178      0      0.0   
23    61    1   2       150   243    1        1      137      1      1.0   
24    40    1   3       140   199    0        1      178      1      1.4   
25    71    0   1       160   302    0        1      162      0      0.4   
26    59    1   2       150   212    1        1      157      0      1.6   
27    51    1   2       110   175    0        1      123      0      0.6   
28    65    0   2       140   417    1        0      157      0      0.8   
29    53    1   2       130   197    1        0      152      0      1.2   
30    41    0   1       105   198    0        1      168      0      0.0   
31    65    1   0       120   177    0        1      140      0      0.4   
32    44    1   1       130   219    0        0      188      0      0.0   
33    54    1   2       125   273    0        0      152      0      0.5   
34    51    1   3       125   213    0        0      125      1      1.4   
35    46    0   2       142   177    0        0      160      1      1.4   
36    54    0   2       135   304    1        1      170      0      0.0   
37    54    1   2       150   232    0        0      165      0      1.6   
38    65    0   2       155   269    0        1      148      0      0.8   
39    65    0   2       160   360    0        0      151      0      0.8   
40    51    0   2       140   308    0        0      142      0      1.5   
41    48    1   1       130   245    0        0      180      0      0.2   
42    45    1   0       104   208    0        0      148      1      3.0   
43    53    0   0       130   264    0        0      143      0      0.4   
44    39    1   2       140   321    0        0      182      0      0.0   
45    52    1   1       120   325    0        1      172      0      0.2   
46    44    1   2       140   235    0        0      180      0      0.0   
47    47    1   2       138   257    0        0      156      0      0.0   
48    53    0   2       128   216    0        0      115      0      0.0   
49    53    0   0       138   234    0        0      160      0      0.0   
50    51    0   2       130   256    0        0      149      0      0.5   
51    66    1   0       120   302    0        0      

In [3]:
df.nunique()

age          41
sex           2
cp            4
trestbps     49
chol        152
fbs           2
restecg       3
thalach      91
exang         2
oldpeak      40
slope         3
ca            5
thal          4
target        2
dtype: int64

In [4]:
df['ca'].unique()

array([0, 2, 1, 3, 4], dtype=int64)

In [5]:
df.ca.value_counts()

0    175
1     65
2     38
3     20
4      5
Name: ca, dtype: int64

In [6]:
df[df['ca']==4]

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
92    52    1   2       138   223    0        1      169      0      0.0   
158   58    1   1       125   220    0        1      144      0      0.4   
163   38    1   2       138   175    0        1      173      0      0.0   
164   38    1   2       138   175    0        1      173      0      0.0   
251   43    1   0       132   247    1        0      143      1      0.1   

     slope  ca  thal  target  
92       2   4     2       1  
158      1   4     3       1  
163      2   4     2       1  
164      2   4     2       1  
251      1   4     3       0

In [7]:
df.loc[df['ca']==4, 'ca']=np.NaN

In [8]:
df['ca'].unique()

array([ 0.,  2.,  1.,  3., nan])

In [9]:
df.thal.value_counts()

2    166
3    117
1     18
0      2
Name: thal, dtype: int64

In [10]:
df[df['thal']==0]

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
48    53    0   2       128   216    0        0      115      0      0.0   
281   52    1   0       128   204    1        1      156      1      1.0   

     slope   ca  thal  target  
48       2  0.0     0       1  
281      1  0.0     0       0

In [11]:
df.loc[df['thal']==0,'thal']=np.NaN

In [12]:
df['thal'].unique()

array([ 1.,  2.,  3., nan])

In [13]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          5
thal        2
target      0
dtype: int64

In [14]:
df = df.fillna(df.median())

In [15]:
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
5     57    1   0       140   192    0        1      148      0      0.4   
6     56    0   1       140   294    0        0      153      0      1.3   
7     44    1   1       120   263    0        1      173      0      0.0   
8     52    1   2       172   199    1        1      162      0      0.5   
9     57    1   2       150   168    0        1      174      0      1.6   
10    54    1   0       140   239    0        1      160      0      1.2   
11    48    0   2       130   275    0        1      139      0      0.2   
12    49    1   1       130   266    0        1      171      0      0.6   
13    64    1   3       110   211    0        0      144      1      1.8   
14    58    0   3       150   283    1        0      162      0      1.0   
15    50    0   2       120   219    0        1      158      0      1.6   
16    58    0   2       120   340    0        1      172      0      0.0   
17    66    0   3       150   226    0        1      114      0      2.6   
18    43    1   0       150   247    0        1      171      0      1.5   
19    69    0   3       140   239    0        1      151      0      1.8   
20    59    1   0       135   234    0        1      161      0      0.5   
21    44    1   2       130   233    0        1      179      1      0.4   
22    42    1   0       140   226    0        1      178      0      0.0   
23    61    1   2       150   243    1        1      137      1      1.0   
24    40    1   3       140   199    0        1      178      1      1.4   
25    71    0   1       160   302    0        1      162      0      0.4   
26    59    1   2       150   212    1        1      157      0      1.6   
27    51    1   2       110   175    0        1      123      0      0.6   
28    65    0   2       140   417    1        0      157      0      0.8   
29    53    1   2       130   197    1        0      152      0      1.2   
30    41    0   1       105   198    0        1      168      0      0.0   
31    65    1   0       120   177    0        1      140      0      0.4   
32    44    1   1       130   219    0        0      188      0      0.0   
33    54    1   2       125   273    0        0      152      0      0.5   
34    51    1   3       125   213    0        0      125      1      1.4   
35    46    0   2       142   177    0        0      160      1      1.4   
36    54    0   2       135   304    1        1      170      0      0.0   
37    54    1   2       150   232    0        0      165      0      1.6   
38    65    0   2       155   269    0        1      148      0      0.8   
39    65    0   2       160   360    0        0      151      0      0.8   
40    51    0   2       140   308    0        0      142      0      1.5   
41    48    1   1       130   245    0        0      180      0      0.2   
42    45    1   0       104   208    0        0      148      1      3.0   
43    53    0   0       130   264    0        0      143      0      0.4   
44    39    1   2       140   321    0        0      182      0      0.0   
45    52    1   1       120   325    0        1      172      0      0.2   
46    44    1   2       140   235    0        0      180      0      0.0   
47    47    1   2       138   257    0        0      156      0      0.0   
48    53    0   2       128   216    0        0      115      0      0.0   
49    53    0   0       138   234    0        0      160      0      0.0   
50    51    0   2       130   256    0        0      149      0      0.5   
51    66    1   0       120   302    0        0      

In [16]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [17]:
duplicated = df[df.duplicated(keep=False)]
duplicated.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
163   38    1   2       138   175    0        1      173      0      0.0   
164   38    1   2       138   175    0        1      173      0      0.0   

     slope   ca  thal  target  
163      2  0.0   2.0       1  
164      2  0.0   2.0       1

In [18]:
df.drop_duplicates(keep='first', inplace=True)

In [19]:
duplicated = df.duplicated().sum()
if duplicated:
    print('Duplicates Row in Dataset are : {}'.format(duplicated))
else:
        print('Dataset contains no Duplicate values')

Dataset contains no Duplicate values


In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 302 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       302 non-null    int64  
 1   sex       302 non-null    int64  
 2   cp        302 non-null    int64  
 3   trestbps  302 non-null    int64  
 4   chol      302 non-null    int64  
 5   fbs       302 non-null    int64  
 6   restecg   302 non-null    int64  
 7   thalach   302 non-null    int64  
 8   exang     302 non-null    int64  
 9   oldpeak   302 non-null    float64
 10  slope     302 non-null    int64  
 11  ca        302 non-null    float64
 12  thal      302 non-null    float64
 13  target    302 non-null    int64  
dtypes: float64(3), int64(11)
memory usage: 35.4 KB


In [21]:
x=df.values
x=np.delete(x,13,axis=1)
y=df['target'].values

In [22]:
x

array([[63.,  1.,  3., ...,  0.,  0.,  1.],
       [37.,  1.,  2., ...,  0.,  0.,  2.],
       [41.,  0.,  1., ...,  2.,  0.,  2.],
       ...,
       [68.,  1.,  0., ...,  1.,  2.,  3.],
       [57.,  1.,  0., ...,  1.,  1.,  3.],
       [57.,  0.,  1., ...,  1.,  1.,  2.]])

In [23]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [24]:
from sklearn.naive_bayes import GaussianNB
modelnb = GaussianNB()

In [25]:
def get_score(modelnb,X_train, X_test, y_train, y_test):
    modelnb.fit(X_train,y_train)
    return modelnb.score(X_test,y_test)

In [26]:
kf=KFold(n_splits=5, random_state=123, shuffle=True)
print(kf)
scores_nb = []
i=1
for train_index, test_index in kf.split(x,y):
    print("Fold ", i)
    print("TRAIN :", train_index, "TEST :", test_index)
    X_train=x[train_index]
    X_test=x[test_index]
    y_train=y[train_index]
    y_test=y[test_index]
    i+=1
    scores_nb.append(get_score(GaussianNB(), X_train, X_test, y_train, y_test))

KFold(n_splits=5, random_state=123, shuffle=True)
Fold  1
TRAIN : [  0   1   2   3   4   5   6   7   8   9  10  12  13  14  15  16  17  18
  21  23  24  25  27  28  32  33  34  36  37  38  39  40  43  44  45  46
  47  48  49  50  51  55  56  57  58  59  60  61  62  63  64  65  66  67
  68  69  70  73  74  76  77  78  79  82  83  84  85  86  87  88  91  92
  93  96  97  98  99 100 101 102 103 104 105 106 108 109 110 111 112 113
 114 116 117 118 119 121 122 123 124 125 126 127 128 129 130 131 132 133
 134 135 136 137 139 140 141 143 145 146 147 148 149 150 151 153 154 155
 156 157 158 159 160 161 162 163 164 165 168 171 172 173 175 176 177 178
 179 180 181 182 183 184 186 187 188 189 192 193 194 196 197 198 199 204
 205 206 207 208 209 210 211 212 213 214 215 217 219 220 221 222 224 225
 226 227 229 230 231 232 233 234 235 236 237 238 239 241 242 243 244 245
 247 248 249 250 251 253 254 255 256 257 261 262 263 264 265 266 269 270
 271 272 273 274 275 276 277 278 279 281 282 284 285 286 2

In [27]:
print("akurasi per fold :")
scores_nb

akurasi per fold :


[0.819672131147541,
 0.819672131147541,
 0.8333333333333334,
 0.9166666666666666,
 0.8166666666666667]

In [28]:
X_test

array([[3.70e+01, 1.00e+00, 2.00e+00, 1.30e+02, 2.50e+02, 0.00e+00,
        1.00e+00, 1.87e+02, 0.00e+00, 3.50e+00, 0.00e+00, 0.00e+00,
        2.00e+00],
       [4.10e+01, 0.00e+00, 1.00e+00, 1.30e+02, 2.04e+02, 0.00e+00,
        0.00e+00, 1.72e+02, 0.00e+00, 1.40e+00, 2.00e+00, 0.00e+00,
        2.00e+00],
       [4.90e+01, 1.00e+00, 1.00e+00, 1.30e+02, 2.66e+02, 0.00e+00,
        1.00e+00, 1.71e+02, 0.00e+00, 6.00e-01, 2.00e+00, 0.00e+00,
        2.00e+00],
       [6.60e+01, 0.00e+00, 3.00e+00, 1.50e+02, 2.26e+02, 0.00e+00,
        1.00e+00, 1.14e+02, 0.00e+00, 2.60e+00, 0.00e+00, 0.00e+00,
        2.00e+00],
       [4.30e+01, 1.00e+00, 0.00e+00, 1.50e+02, 2.47e+02, 0.00e+00,
        1.00e+00, 1.71e+02, 0.00e+00, 1.50e+00, 2.00e+00, 0.00e+00,
        2.00e+00],
       [7.10e+01, 0.00e+00, 1.00e+00, 1.60e+02, 3.02e+02, 0.00e+00,
        1.00e+00, 1.62e+02, 0.00e+00, 4.00e-01, 2.00e+00, 2.00e+00,
        2.00e+00],
       [4.40e+01, 1.00e+00, 1.00e+00, 1.30e+02, 2.19e+02, 0.00e+00,
  

In [29]:
y_test

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [30]:
modelnb.fit(X_train,y_train)

GaussianNB()

In [31]:
modelnb.predict_proba(X_test)

array([[9.47351777e-01, 5.26482231e-02],
       [9.62525232e-04, 9.99037475e-01],
       [4.17213304e-03, 9.95827867e-01],
       [7.44556492e-01, 2.55443508e-01],
       [4.06622893e-02, 9.59337711e-01],
       [2.02927941e-01, 7.97072059e-01],
       [2.59059692e-03, 9.97409403e-01],
       [4.00917350e-03, 9.95990827e-01],
       [3.41326478e-02, 9.65867352e-01],
       [3.35493919e-03, 9.96645061e-01],
       [4.79027753e-03, 9.95209722e-01],
       [2.19819104e-01, 7.80180896e-01],
       [1.04478514e-02, 9.89552149e-01],
       [9.44350482e-03, 9.90556495e-01],
       [7.83026147e-03, 9.92169739e-01],
       [1.83232177e-03, 9.98167678e-01],
       [1.37812933e-01, 8.62187067e-01],
       [2.31768123e-01, 7.68231877e-01],
       [4.64520998e-01, 5.35479002e-01],
       [8.13235381e-02, 9.18676462e-01],
       [5.14516365e-02, 9.48548364e-01],
       [6.15921955e-02, 9.38407805e-01],
       [3.43183883e-02, 9.65681612e-01],
       [9.70456040e-01, 2.95439598e-02],
       [9.999987

In [32]:
prediksi = modelnb.predict(X_test)
prediksi

array([0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0], dtype=int64)

In [33]:
# import confusion_matrix model
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, prediksi)

array([[17,  7],
       [ 4, 32]], dtype=int64)

In [34]:
# Menghitung nilai akurasi dari klasifikasi naive bayes 
from sklearn.metrics import classification_report
print(classification_report(y_test, prediksi))

              precision    recall  f1-score   support

           0       0.81      0.71      0.76        24
           1       0.82      0.89      0.85        36

    accuracy                           0.82        60
   macro avg       0.82      0.80      0.80        60
weighted avg       0.82      0.82      0.81        60



In [35]:
# test manual
test = [[52, 1, 1, 134, 201, 0, 1, 158, 0, 0.8, 2, 1, 2]]
predicted= modelnb.predict(test)
print("hasil prediksi :"),predicted

hasil prediksi :


(None, array([1], dtype=int64))

In [36]:
predicted_proba=modelnb.predict_proba(test)
print("hasil probabilitas:"),predicted_proba

hasil probabilitas:


(None, array([[0.02588669, 0.97411331]]))